# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TeacherKlas' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeacherKlas
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  # target 'TeacherKlas-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

  target 'TeacherKlasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TeacherKlas-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeacherKlas-tvOS

  target 'TeacherKlas-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
