// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const IS_LOADING = 'IS_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGGED_OUT = 'LOGGED_OUT';

// COMPLETE PROFILE TYPES
export const CHANGE_INPUT = 'CHANGE_INPUT';

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';

export const ADD_WORK = 'ADD_WORK';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';

export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';

// UPLOAD IMAGE TYPES
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';